# Generated by Django 5.2.10 on 2026-02-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_display_amount_order_paid_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='display_amount',
        ),
    ]
