# Generated by Django 5.2.10 on 2026-02-11 12:44

from django.db import migrations
from django.utils import timezone


def sync_payment_fields(apps, schema_editor):
    """
    Sync paid field with payment_status for all existing orders.
    This ensures data consistency for orders created before the strict sync logic.
    """
    Order = apps.get_model('orders', 'Order')
    
    # Find all orders with payment_status='completed' but paid=False
    orders_to_fix = Order.objects.filter(payment_status='completed', paid=False)
    count = orders_to_fix.count()
    
    # Update them
    for order in orders_to_fix:
        order.paid = True
        # Set paid_at if not already set
        if not order.paid_at:
            order.paid_at = timezone.now()
        order.save()
    
    print(f"[SUCCESS] Synced {count} orders: payment_status='completed' -> paid=True")


def reverse_sync(apps, schema_editor):
    """
    Reverse migration - set paid back to False for completed payments
    (Not recommended in production, but provided for completeness)
    """
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(payment_status='completed').update(paid=False, paid_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_display_amount'),
    ]

    operations = [
        migrations.RunPython(sync_payment_fields, reverse_sync),
    ]
